spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ec-202001e
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: 自分のメールアドレスを入れる
    password: アプリパスを入れる
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true 
